package ch.kdev.todo.server;

import junit.framework.TestCase;

import org.junit.Test;

import ch.kdev.todo.domain.Project;
import ch.kdev.todo.server.service.ProjectService;

public class ProjectServiceTest extends TestCase {
   
   ProjectService projectService;

   @Override
   public void setUp() {
       this.projectService = new ProjectService();
   }

   @Test
   public void testPersistProject() {
      Project testProject = new Project();
      
      testProject.setName("TestProjectName");
      testProject.setDescription("This is a test project, generated by a JUnit-Test. Should be removed the method testRemoveProject()");
      
      this.projectService.persist(testProject);
   }

}
