// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package ch.kdev.todo.client.view.resources;
import com.google.gwt.resources.client.CssResource;
import com.google.gwt.resources.client.CssResource.ClassName;
interface AppStyleDesktop extends CssResource {
  
  String validationFailedBorder();
}

