// DO NOT EDIT
// Automatically generated by com.google.gwt.resources.css.InterfaceGenerator
package ch.kdev.todo.client.view.resources;
import com.google.gwt.resources.client.CssResource;

interface ClientStyle extends CssResource {

   String validationFailedBorder();
}
